### ISSUE TITLE
Graphical Error on Firefox

### ISSUE THREAD

**Issue by montymxb** [ParsePlatform/Docs#425]
Just noted the following graphical error in firefox for [docs.parseplatform.org](http://docs.parseplatform.org/).
![shot](https://cloud.githubusercontent.com/assets/5070304/24819572/fe37bf80-1b99-11e7-934c-f468915fac0f.png)
It looks like the svg is getting cut off vertically for all icons. Looking at the css it seems like there is a transform being done to translate the icon up on the y axis. 
```css
transform: translateY(-50%);
``` 
You can find this in [_site/css/docs.css on line 767](https://github.com/parse-community/docs/blob/2d818c6bb029a56b101b69814c8aab3a1717714c/_site/css/docs.css#L767). It's not terrible, but it's  a bit unsightly given the clipping.

As far as I'm aware the same affect could be achieved by instead using a negative margin:
```css
margin-top: -24px;
```
This _should_ look the same as the old line in all other browsers, while removing the clipping in firefox. I'm opening this up as an issue to see if others have experienced or can verify this. Also to see if perhaps I missed something in regards to how that css is needed for other elements on other pages.

Also, and this is unrelated, the description for this repository has an `https` link although the site does not support https currently.
```
These are the markdown sources for all the platform guides of Parse. https://docs.parseplatform.org
```

**Comment by flovilmart** [comment]
fixed the https link. not sure about the CSS, my frontend days are way back. @ziad-saab, what do you think?

**Comment by montymxb** [comment]
@flovilmart any interest in patching this up? The issue still stands as it is. 

There are multiple ways of rectifying this, the above solution being just one. I primarily work with html/css/js on the daily, in case you were curious about my insight into this. I'm willing to put up a PR to address when I have some time to address this.

**Comment by flovilmart** [comment]
Yes go with a PR, I'm quite rusty with CSS as my primary is backend, infra, dev-ops and iOS :)

**Comment by flovilmart** [comment]
Closing as solved!
